# See https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:
- job: Test
  pool:
    vmImage: Ubuntu 16.04
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.7"
      architecture: x64
  - script: pip3 install networkx pylint tqdm
    displayName: Install Python packages
  - script: pylint physlr
    displayName: Run pylint
  - script: pip3 install .
    displayName: Run pip
  - script: sudo apt-get install clang-tidy-4.0
    displayName: Install clang-tidy-4.0
  - script: clang-tidy -warnings-as-errors='*' indexlr/*.cc
    displayName: Run clang-tidy