# See https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:
- job: Test
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.7"
      architecture: x64
  - script: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
  - script: conda create --yes --quiet --name physlr
    displayName: Create Anaconda environment
  - script: |
      source activate physlr
      conda install --yes -c conda-forge -c bioconda --file requirements.txt
    displayName: Install dependencies
  - script: |
      source activate physlr
      conda install --yes -c bioconda -c conda-forge clang clang-tools openmp
    displayName: Conda Install clang-format and clang-tidy
  - script: sudo apt-get install -qq libboost-dev
    displayName: Install boost
  - script: pip3 install pylint .
    displayName: Install Python packages
  - script: make lint
    displayName: Run pylint
  - script: |
      source activate physlr
      export CPPFLAGS="-isystem $CONDA_PREFIX/include/ $CPPFLAGS"
      export LDFLAGS="-L$CONDA_PREFIX//lib -lbtllib $LDFLAGS"
      make -C src all
    displayName: Compile C++ executables
  - script: |
      source activate physlr
      make -C src lint
    displayName: Run clang-format and clang-tidy
  - script: |
      source activate physlr
      make -C src check
    displayName: Test C++ executables
  - script: make -C data test python_executable=python m=1 prune_branches=1 prune_bridges=1
    displayName: Test Python modules
